name: github pages

on:
  push:
    branches:
      - master  # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: setup
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - run: python3 -m pip install -U -r requirements.txt
      - run: ./extract_phoneme_list.py
      - run: ./ipatope.py

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: master  # deploying branch
